### ISSUE TITLE
Improve .gitignore to skip irrelevant files

### ISSUE THREAD

**Issue by donmutti** [samartemy-org/test-yandex#1]
Edit .gitignore to skip the following files:

- MacOS system Files:
  - .DS_Store
  - Thumbs.db

- IDEA project and build files:
  - .idea/
  - *.iml
  - *.ipr
  - *.iws
  - out/

**Comment by SamArtemy** [comment]
How skip files? Do I need to create a individual branch, delete the files and commit changes to the new branch?

**Comment by donmutti** [comment]
Please refer to https://git-scm.com/docs/gitignore on how to use gitignore file
